"use client";

import { useState, useEffect, useRef } from "react";
import {
  GraduationCap,
  Link2,
  Copy,
  Check,
  Download,
  ExternalLink,
  Star,
  Target,
  Briefcase,
  Loader2,
} from "lucide-react";
import Card from "../../components/ui/card";
import Badge from "../../components/ui/badge";
import ProgressBar from "../../components/ui/progressbar";
import SkillRadar from "../../components/charts/skillradar";
import DashboardHeader from "../../components/layout/dashboardheader";
import { getCurrentStudent } from "../../lib/mock-data";
import { getMatchBg, getInitials } from "../../lib/utils";

export default function PortfolioPage() {
  const [mounted, setMounted] = useState(false);
  const [copied, setCopied] = useState(false);
  const [generatingPdf, setGeneratingPdf] = useState(false);
  const portfolioRef = useRef<HTMLDivElement>(null);
  useEffect(() => { setMounted(true); }, []);

  const student = mounted ? getCurrentStudent() : null;

  const handleCopy = () => {
    navigator.clipboard.writeText(portfolioUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = async () => {
    if (generatingPdf) return;
    const s = getCurrentStudent();
    if (!s) return;
    setGeneratingPdf(true);
    try {
      const { domToPng } = await import("modern-screenshot");
      const { jsPDF } = await import("jspdf");

      const { profile, hardSkills, softSkills, projects, careerMatches } = s;
      const all = [...hardSkills, ...softSkills];
      const score = Math.round(careerMatches.reduce((sum, c) => sum + c.matchPercentage, 0) / careerMatches.length);

      const html = `
        <div style="font-family:system-ui,-apple-system,sans-serif;background:#ffffff;color:#1e293b;padding:20px;width:700px;">
          <div style="display:flex;align-items:center;gap:16px;margin-bottom:16px;padding-bottom:14px;border-bottom:1.5px solid #e2e8f0;">
            <div style="width:48px;height:48px;border-radius:50%;background:linear-gradient(135deg,#2563eb,#7c3aed);display:flex;align-items:center;justify-content:center;flex-shrink:0;">
              <span style="color:#fff;font-size:18px;font-weight:700;">${getInitials(profile.name)}</span>
            </div>
            <div style="flex:1;">
              <div style="font-size:17px;font-weight:700;color:#0f172a;margin-bottom:2px;">${profile.name}</div>
              <div style="font-size:12px;color:#475569;">${profile.major} — Kelas ${profile.grade}</div>
              <div style="font-size:10px;color:#94a3b8;margin-top:1px;">Portfolio generated by SkillMatch</div>
            </div>
            <div style="text-align:center;">
              <div style="font-size:26px;font-weight:700;color:#2563eb;">${score}%</div>
              <div style="font-size:10px;color:#64748b;">Readiness Score</div>
            </div>
          </div>

          <div style="margin-bottom:14px;">
            <div style="font-size:11px;font-weight:700;color:#334155;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:6px;">Skills</div>
            <div style="display:flex;flex-wrap:wrap;gap:5px;">
              ${all.map(sk => `<span style="padding:3px 8px;background:#eff6ff;color:#1d4ed8;border-radius:999px;font-size:10px;font-weight:500;">${sk.name} (${sk.level}%)</span>`).join("")}
            </div>
          </div>

          <div style="margin-bottom:14px;">
            <div style="font-size:11px;font-weight:700;color:#334155;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:6px;">Projects</div>
            <div style="display:flex;flex-direction:column;gap:6px;">
              ${projects.map(p => `
                <div style="padding:8px 12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;">
                  <div style="font-size:12px;font-weight:600;color:#0f172a;margin-bottom:2px;">${p.title}</div>
                  <div style="font-size:10px;color:#64748b;margin-bottom:4px;">${p.description}</div>
                  <div style="display:flex;flex-wrap:wrap;gap:3px;">
                    ${p.skills.map(sk => `<span style="padding:1px 6px;background:#dbeafe;color:#1e40af;border-radius:3px;font-size:9px;font-weight:500;">${sk}</span>`).join("")}
                  </div>
                </div>
              `).join("")}
            </div>
          </div>

          <div>
            <div style="font-size:11px;font-weight:700;color:#334155;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:6px;">Top Career Matches</div>
            <div style="display:flex;flex-direction:column;gap:5px;">
              ${careerMatches.slice(0, 3).map(c => `
                <div style="display:flex;align-items:center;justify-content:space-between;padding:8px 12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;">
                  <div>
                    <div style="font-size:12px;font-weight:600;color:#0f172a;">${c.title}</div>
                    <div style="font-size:10px;color:#64748b;">${c.category}</div>
                  </div>
                  <div style="font-size:12px;font-weight:700;color:#2563eb;">${c.matchPercentage}%</div>
                </div>
              `).join("")}
            </div>
          </div>
        </div>`;

      const container = document.createElement("div");
      container.style.position = "fixed";
      container.style.left = "-9999px";
      container.style.top = "0";
      container.innerHTML = html;
      document.body.appendChild(container);

      const dataUrl = await domToPng(container.firstElementChild as HTMLElement, {
        scale: 2,
        backgroundColor: "#ffffff",
      });

      document.body.removeChild(container);

      const img = new Image();
      img.src = dataUrl;
      await new Promise<void>((r) => { img.onload = () => r(); });

      const pdfW = 210;
      const pdfH = (img.height * pdfW) / img.width;
      const margin = 5;
      const contentW = pdfW - margin * 2;

      const pdf = new jsPDF("p", "mm", "a4");
      let pos = margin;
      const pageH = 297;

      if (pdfH <= pageH - margin * 2) {
        pdf.addImage(dataUrl, "PNG", margin, pos, contentW, pdfH);
      } else {
        let rem = pdfH;
        while (rem > 0) {
          pdf.addImage(dataUrl, "PNG", margin, pos, contentW, pdfH);
          rem -= pageH;
          pos += pageH;
          if (rem > 0) pdf.addPage();
        }
      }

      pdf.save(`Portfolio_${profile.name.replace(/\s+/g, "_")}.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setGeneratingPdf(false);
    }
  };

  if (!mounted || !student) return null;
  const { profile, hardSkills, softSkills, projects, careerMatches } = student;
  const allSkills = [...hardSkills, ...softSkills];
  const readinessScore = Math.round(careerMatches.reduce((sum, c) => sum + c.matchPercentage, 0) / careerMatches.length);
  const portfolioUrl = mounted
    ? `${window.location.origin}/portfolio/${profile.name.toLowerCase().replace(/\s+/g, "-")}`
    : `/portfolio/${profile.name.toLowerCase().replace(/\s+/g, "-")}`;

  return (
    <div>
      <DashboardHeader
        title="Portfolio Kamu"
        subtitle="Portfolio otomatis dari data skill dan proyek kamu"
      />

      {/* Portfolio Preview Card */}
      <Card className="mb-8 bg-gradient-to-br from-primary/5 to-secondary/5 border-primary/20">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-4">
          <h3 className="font-semibold text-foreground">Portfolio Public URL</h3>
          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-3 py-1.5 text-sm bg-card border border-border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
              {copied ? "Tersalin!" : "Copy Link"}
            </button>
            <button
              onClick={handleDownloadPdf}
              disabled={generatingPdf}
              className="flex items-center gap-2 px-3 py-1.5 text-sm bg-primary text-white border border-primary rounded-lg hover:bg-primary-dark transition-colors disabled:opacity-50"
            >
              {generatingPdf ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              {generatingPdf ? "Generating..." : "Download PDF"}
            </button>
          </div>
        </div>
        <a
          href={portfolioUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 px-4 py-2.5 bg-card rounded-lg border border-border hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors cursor-pointer"
        >
          <Link2 className="w-4 h-4 text-muted" />
          <span className="text-sm text-foreground font-mono flex-1 truncate">{portfolioUrl}</span>
          <ExternalLink className="w-3 h-3 text-muted" />
        </a>
      </Card>

      <div className="rounded-2xl p-1 bg-gray-200 dark:bg-gray-700 border border-gray-300 dark:border-gray-600">
        <div ref={portfolioRef} className="bg-card dark:bg-gray-800 rounded-xl p-6 text-foreground">
        {/* Profile Header */}
        <div className="flex flex-wrap items-center gap-4 mb-6 pb-6 border-b border-border dark:border-gray-700">
          <div className="w-16 h-16 rounded-full bg-gradient-to-br from-blue-600 to-purple-600 flex items-center justify-center flex-shrink-0">
            <span className="text-xl font-bold text-white">{getInitials(profile.name)}</span>
          </div>
          <div>
            <h2 className="text-xl font-bold text-foreground dark:text-white">{profile.name}</h2>
            <p className="text-sm text-muted dark:text-gray-400">{profile.major} - Kelas {profile.grade}</p>
            <p className="text-xs text-muted/60 dark:text-gray-500 mt-1">Portfolio generated by SkillMatch</p>
          </div>
          <div className="ml-auto text-center">
            <div className="text-3xl font-bold text-blue-600 dark:text-blue-400">{readinessScore}%</div>
            <p className="text-xs text-muted dark:text-gray-400">Readiness Score</p>
          </div>
        </div>

        {/* Skills */}
        <div className="mb-6">
          <h3 className="text-sm font-bold text-foreground dark:text-gray-200 uppercase tracking-wider mb-3">Skills</h3>
          <div className="flex flex-wrap gap-2">
            {allSkills.map((skill) => (
              <span key={skill.id} className="px-3 py-1 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-full text-xs font-medium">
                {skill.name} ({skill.level}%)
              </span>
            ))}
          </div>
        </div>

        {/* Projects */}
        <div className="mb-6">
          <h3 className="text-sm font-bold text-foreground dark:text-gray-200 uppercase tracking-wider mb-3">Projects</h3>
          <div className="space-y-3">
            {projects.map((project) => (
              <div key={project.id} className="p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg border border-gray-200 dark:border-gray-600">
                <h4 className="font-medium text-foreground dark:text-white text-sm">{project.title}</h4>
                <p className="text-xs text-muted dark:text-gray-400 mt-1">{project.description}</p>
                <div className="flex flex-wrap gap-1 mt-2">
                  {project.skills.map((skill) => (
                    <span key={skill} className="px-2 py-0.5 bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 rounded text-[10px] font-medium">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Career Matches */}
        <div>
          <h3 className="text-sm font-bold text-foreground dark:text-gray-200 uppercase tracking-wider mb-3">Top Career Matches</h3>
          <div className="space-y-2">
            {careerMatches.slice(0, 3).map((match) => (
              <div key={match.id} className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg border border-gray-200 dark:border-gray-600">
                <div>
                  <p className="font-medium text-foreground dark:text-white text-sm">{match.title}</p>
                  <p className="text-xs text-muted dark:text-gray-400">{match.category}</p>
                </div>
                <span className="text-sm font-bold text-blue-600 dark:text-blue-400">{match.matchPercentage}%</span>
              </div>
            ))}
          </div>
        </div>
      </div>
      </div>

      {/* Interactive Preview Section (not in PDF) */}
      <div className="mt-8">
        <h3 className="text-sm font-bold text-foreground uppercase tracking-wider mb-4">Interactive Preview</h3>
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Profile Card */}
          <Card className="text-center">
            <div className="w-20 h-20 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl font-bold text-white">{getInitials(profile.name)}</span>
            </div>
            <h2 className="text-xl font-bold text-foreground">{profile.name}</h2>
            <p className="text-sm text-muted">{profile.major} - Kelas {profile.grade}</p>
            <div className="mt-4">
              <div className="text-3xl font-bold text-primary">{readinessScore}%</div>
              <p className="text-xs text-muted">Career Readiness Score</p>
            </div>
            <ProgressBar
              value={readinessScore}
              size="sm"
              color={readinessScore >= 80 ? "success" : "primary"}
              showValue={false}
              className="mt-2"
            />
          </Card>

          {/* Skills Radar */}
          <Card className="lg:col-span-2">
            <SkillRadar skills={allSkills.slice(0, 8)} title="Skill Profile" />
          </Card>
        </div>
      </div>
    </div>
  );
}
